# Generated by Django 5.2 on 2025-04-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_customer_user_has_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_resume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_applicant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_recruiter',
        ),
    ]
